services:
  marknote:
    image: odevsa/marknote:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: marknote
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - DATA_DIR=/app/data/base
      - NOTES_DIR=/app/data/notes
      - JWT_SECRET=change_this_to_a_secure_random_secret_32_chars
    volumes:
      - ./.marknote/data/base:/app/data/base
      - ./.marknote/data/notes:/app/data/notes

